#!/bin/sh

zip -j function.zip captions/*.js
zip -rq function.zip node_modules

aws lambda update-function-code \
  --function-name dailyfunctal \
  --zip-file fileb://function.zip \
  --region us-east-1

rm function.zip